services:
  auth-svc:
    build:
      context: ./auth-svc
    ports:
      - "5000:5000"
    networks:
      - project1-network
    env_file:
      - .env

  enterdata-app:
    build:
      context: ./enterdata-app
    ports:
      - "4000:4000"
    depends_on:
      - auth-svc
      - player-db
    networks:
      - project1-network
    env_file:
      - .env

  analytics-svc:
    build:
      context: ./analytics-svc
    depends_on:
      - stats-db
    networks:
      - project1-network
    env_file:
      - .env

  showresults-app:
    build:
      context: ./showresults-app
    ports:
      - "3000:3000"
    depends_on:
      - auth-svc
      - stats-db
    networks:
      - project1-network
    env_file:
      - .env

  player-db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_db:/docker-entrypoint-initdb.d
    networks:
      - project1-network
    env_file:
      - .env

  stats-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - project1-network
    env_file:
      - .env

networks:
  project1-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:

