apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  create_table.sql: |
    CREATE TABLE IF NOT EXISTS players (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      points INT NOT NULL
    );
