apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterdata-app-deploy
spec:
  selector:
    matchLabels:
      app: enterdata-app
  template:
    metadata:
      labels:
        app: enterdata-app
    spec:
      containers:
        - name: enterdata-app
          image: victortran1449/enterdata-app:latest
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: app-configmap
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
